name: First workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print welcome
        run: echo "Welcome to our page"
      - name: Print goodbye
        run: echo "Goodbye and thanks for visiting"



